class AppStrings {
  static const Map<String, Map<String, String>> translations = {
    'en': {
      'profile': 'Profile',
      'edit': 'Edit',
      'save': 'Save',
      'hi': 'Hi',
      'tasks': 'Tasks',
      'pending': 'PENDING',
      'exams': 'Exams',
      'upcoming': 'UPCOMING',
      'accountSecurity': 'ACCOUNT SECURITY',
      'name': 'NAME',
      'email': 'EMAIL',
      'password': 'PASSWORD',
      'preferences': 'PREFERENCES',
      'language': 'Language',
      'selectLanguage': 'Select Language',
      'english': 'English',
      'thai': 'ไทย',
      'darkTheme': 'Dark Theme',
      'darkMode': 'Dark Mode',
      'signOut': 'Sign Out',
      'addPlan': 'Add Plan',
      'tasks_label': 'Tasks',
      'exams_label': 'Exams',
      'subject': 'Subject',
      'activity': 'Activity',
      'dueDate': 'Due Date',
      'time': 'TIME',
      'location': 'Location',
      'briefNotes': 'Brief Notes',
      'week': 'WEEK',
      'completed': 'Completed',
      'detail': 'Detail',
      'home': 'Home',
      'settings': 'Settings',
    },
    'th': {
      'profile': 'โปรไฟล์',
      'edit': 'แก้ไข',
      'save': 'บันทึก',
      'hi': 'สวัสดี',
      'tasks': 'งาน',
      'pending': 'รอดำเนิน',
      'exams': 'สอบ',
      'upcoming': 'รอสอบ',
      'accountSecurity': 'ความปลอดภัยบัญชี',
      'name': 'ชื่อ',
      'email': 'อีเมล',
      'password': 'รหัสผ่าน',
      'preferences': 'ความชอบ',
      'language': 'ภาษา',
      'selectLanguage': 'เลือกภาษา',
      'english': 'English',
      'thai': 'ไทย',
      'darkTheme': 'โหมดมืด',
      'darkMode': 'โหมดมืด',
      'signOut': 'ออกจากระบบ',
      'addPlan': 'เพิ่มแผน',
      'tasks_label': 'งาน',
      'exams_label': 'สอบ',
      'subject': 'วิชา',
      'activity': 'กิจกรรม',
      'dueDate': 'กำหนดส่ง',
      'time': 'เวลา',
      'location': 'สถานที่',
      'briefNotes': 'หมายเหตุ',
      'week': 'สัปดาห์',
      'completed': 'เสร็จแล้ว',
      'detail': 'รายละเอียด',
      'home': 'หน้าแรก',
      'settings': 'ตั้งค่า',
    },
  };

  static String get(String key, String language) {
    return translations[language]?[key] ?? translations['en']![key]!;
  }
}
