class AppStrings {
  static const Map<String, Map<String, String>> translations = {
    'en': {
      'profile': 'Profile',
      'edit': 'Edit',
      'save': 'Save',
      'hi': 'Hi',
      'tasks': 'Tasks',
      'pending': 'PENDING',
      'exams': 'Exams',
      'upcoming': 'UPCOMING',
      'accountSecurity': 'Account Security',
      'name': 'Name',
      'email': 'Email',
      'password': 'Password',
      'preferences': 'Preferences',
      'security': 'Security',
      'language': 'Language',
      'selectLanguage': 'Select Language',
      'english': 'English',
      'thai': 'ไทย',
      'darkTheme': 'Dark Theme',
      'darkMode': 'Dark Mode',
      'signOut': 'Sign Out',
      'signUp': 'Sign Up',
      'addPlan': 'Add Plan',
      'tasks_label': 'Tasks',
      'exams_label': 'Exams',
      'subject': 'Subject',
      'activity': 'Activity',
      'dueDate': 'Due Date',
      'time': 'TIME',
      'location': 'Location',
      'briefNotes': 'Brief Notes',
      'week': 'WEEK',
      'completed': 'Completed',
      'detail': 'Detail',
      'home': 'Home',
      'settings': 'Settings',
      'finished': 'Finished',
      'noCompletedTasksYet': 'No completed tasks yet',
      'changePassword': 'Change Password?',
      'moveToPending': 'Move to Pending',
      'done': 'Done',
      'task': 'TASK',
      'exam': 'EXAM',
      'tasksUpper': 'TASKS',
      'examsUpper': 'EXAMS',
      'noAdditionalNotes': 'No additional notes.',
      'selectDate': 'Select a date',
      'selectTime': 'Select a time',
      'pleaseEnterSubject': 'Please enter a subject.',
      'pleaseEnterActivity': 'Please enter an activity.',
      'pleaseEnterExamLocation': 'Please enter a location for exams.',
      'pleaseSelectDueDate': 'Please select a due date.',
      'pleaseSelectTime': 'Please select a time.',
      'cancel': 'Cancel',
      'sendLink': 'Send Link',
      'resetPasswordHint': "We'll send a password reset link to your email address.",
      'changePasswordHint': 'Enter your current password and set a new password.',
      'resetPasswordGoogleHint': 'This account was created with Google Sign-In. Please sign in with Google.',
      'resetLinkSent': 'Password reset link has been sent to',
      'failedToSendEmail': 'Failed to send reset email',
      'currentPassword': 'Current Password',
      'newPassword': 'New Password',
      'confirmNewPassword': 'Confirm New Password',
      'enterCurrentPassword': 'Enter current password',
      'enterNewPassword': 'Enter new password',
      'confirmYourNewPassword': 'Confirm your new password',
      'changePasswordAction': 'Change Password',
      'passwordChangedSuccess': 'Password changed successfully',
      'currentPasswordIncorrect': 'Current password is incorrect',
      'passwordChangeRequiresRecentLogin': 'For security, please sign in again before changing your password.',
      'passwordAccountOnly': 'This account uses Google Sign-In and has no password to change.',
      'cannotUseSamePassword': 'New password must be different from current password',
      'passwordResetNeedsPasswordAccount': 'This account uses Google Sign-In. Reset password is unavailable.',
      'confirmSignOutTitle': 'Sign Out',
      'confirmSignOutMessage': 'Are you sure you want to sign out?',
      'confirmSignOutAction': 'Sign Out',
      'loginTagline': 'Your companion for academic achievement and organized student life.',
      'forgotPassword': 'Forgot Password?',
      'resetPasswordTitle': 'Reset Password',
      'resetPasswordDescription': "Enter your email address and we'll send you a link to reset your password.",
      'enterYourEmail': 'Enter your email',
      'signIn': 'Sign In',
      'orContinueWith': 'Or continue with',
      'googleSignInSemantic': 'Google sign-in',
      'noAccountPrompt': "Don't have an account? ",
      'emailAddress': 'Email Address',
      'enterEmailAddress': 'Enter Email Address',
      'pleaseEnterEmailAddress': 'Please enter email address',
      'pleaseEnterValidEmailAddress': 'Please enter a valid email address',
      'pleaseEnterPassword': 'Please enter password',
      'passwordMinLength': 'Password must be at least 8 characters',
      'signInFailed': 'Sign in failed',
      'noAccountFound': 'No account found with this email',
      'incorrectPassword': 'Incorrect password',
      'invalidCredentials': 'Incorrect email or password',
      'invalidEmailAddress': 'Invalid email address',
      'accountDisabled': 'This account has been disabled',
      'googleSignInFailed': 'Google sign-in failed',
      'googleSignInCancelled': 'Google sign-in cancelled',
      'createAccount': 'Create Account',
      'signupSubtitle': 'Sign up to get started with PLAZO',
      'alreadyHaveAccountPrompt': 'Already have an account? ',
      'fullName': 'Full Name',
      'enterFullName': 'Enter your full name',
      'pleaseEnterYourName': 'Please enter your name',
      'confirmPassword': 'Confirm Password',
      'pleaseConfirmPassword': 'Please confirm your password',
      'passwordsDoNotMatch': 'Passwords do not match',
      'signUpFailed': 'Sign up failed',
      'weakPassword': 'Password is too weak',
      'emailAlreadyInUse': 'Email is already in use',
      'lastLogin': 'Last Login',
      'lastLoginNever': 'Never',
      'activeSessions': 'Active Sessions',
      'currentDevice': 'This Device (Current)',
      'device': 'Device',
      'lastActivity': 'Last Activity',
      'manageDevices': 'Manage',
      'securityAlerts': 'Security Alerts',
      'noActiveAlerts': 'No alerts',
      'recentActivity': 'Recent Activity',
      'viewActivityLog': 'View logs',
      'deleteAccount': 'Delete Account',
      'deleteAccountButton': 'Delete My Account',
      'deleteAccountConfirmTitle': 'Delete Account',
      'deleteAccountConfirmMessage': 'Are you sure? This action cannot be undone. All your data will be permanently deleted.',
      'deleteAccountWarning': 'Warning: This will delete your account and all associated data permanently.',
      'accountDeleted': 'Account deleted successfully',
      'dataDeletedWarning': 'Your account and all data have been permanently deleted.',
      'viewPrivacyPolicy': 'View Privacy Policy',
      'privacyPolicy': 'Privacy Policy',
    },
    'th': {
      'profile': 'โปรไฟล์',
      'edit': 'แก้ไข',
      'save': 'บันทึก',
      'hi': 'สวัสดี',
      'tasks': 'งาน',
      'pending': 'รอดำเนิน',
      'exams': 'สอบ',
      'upcoming': 'รอสอบ',
      'accountSecurity': 'ความปลอดภัยบัญชี',
      'name': 'ชื่อ',
      'email': 'อีเมล',
      'password': 'รหัสผ่าน',
      'preferences': 'ความชอบ',
      'security': 'ความปลอดภัย',
      'language': 'ภาษา',
      'selectLanguage': 'เลือกภาษา',
      'english': 'English',
      'thai': 'ไทย',
      'darkTheme': 'โหมดมืด',
      'darkMode': 'โหมดมืด',
      'signOut': 'ออกจากระบบ',
      'signUp': 'สมัครสมาชิก',
      'addPlan': 'เพิ่มแผน',
      'tasks_label': 'งาน',
      'exams_label': 'สอบ',
      'subject': 'วิชา',
      'activity': 'กิจกรรม',
      'dueDate': 'กำหนดส่ง',
      'time': 'เวลา',
      'location': 'สถานที่',
      'briefNotes': 'หมายเหตุ',
      'week': 'สัปดาห์',
      'completed': 'เสร็จแล้ว',
      'detail': 'รายละเอียด',
      'home': 'หน้าแรก',
      'settings': 'ตั้งค่า',
      'finished': 'เสร็จสิ้น',
      'noCompletedTasksYet': 'ยังไม่มีงานที่เสร็จแล้ว',
      'changePassword': 'เปลี่ยนรหัสผ่าน?',
      'moveToPending': 'ย้ายไปงานค้าง',
      'done': 'เสร็จแล้ว',
      'task': 'งาน',
      'exam': 'สอบ',
      'tasksUpper': 'งาน',
      'examsUpper': 'สอบ',
      'noAdditionalNotes': 'ไม่มีหมายเหตุเพิ่มเติม',
      'selectDate': 'เลือกวันที่',
      'selectTime': 'เลือกเวลา',
      'pleaseEnterSubject': 'กรุณากรอกวิชา',
      'pleaseEnterActivity': 'กรุณากรอกกิจกรรม',
      'pleaseEnterExamLocation': 'กรุณากรอกสถานที่สอบ',
      'pleaseSelectDueDate': 'กรุณาเลือกวันครบกำหนด',
      'pleaseSelectTime': 'กรุณาเลือกเวลา',
      'cancel': 'ยกเลิก',
      'sendLink': 'ส่งลิงก์',
      'resetPasswordHint': 'เราจะส่งลิงก์รีเซ็ตรหัสผ่านไปที่ที่อยู่อีเมลของคุณ',
      'changePasswordHint': 'กรอกรหัสผ่านปัจจุบัน แล้วตั้งรหัสผ่านใหม่ได้เลย',
      'resetPasswordGoogleHint': 'บัญชีนี้สมัครด้วย Google Sign-In กรุณาเข้าสู่ระบบด้วย Google',
      'resetLinkSent': 'ลิงก์รีเซ็ตรหัสผ่านถูกส่งไปที่',
      'failedToSendEmail': 'ไม่สามารถส่งอีเมลได้',
      'currentPassword': 'รหัสผ่านปัจจุบัน',
      'newPassword': 'รหัสผ่านใหม่',
      'confirmNewPassword': 'ยืนยันรหัสผ่านใหม่',
      'enterCurrentPassword': 'กรอกรหัสผ่านปัจจุบัน',
      'enterNewPassword': 'กรอกรหัสผ่านใหม่',
      'confirmYourNewPassword': 'ยืนยันรหัสผ่านใหม่ของคุณ',
      'changePasswordAction': 'เปลี่ยนรหัสผ่าน',
      'passwordChangedSuccess': 'เปลี่ยนรหัสผ่านสำเร็จ',
      'currentPasswordIncorrect': 'รหัสผ่านปัจจุบันไม่ถูกต้อง',
      'passwordChangeRequiresRecentLogin': 'เพื่อความปลอดภัย กรุณาเข้าสู่ระบบใหม่ก่อนเปลี่ยนรหัสผ่าน',
      'passwordAccountOnly': 'บัญชีนี้ใช้ Google Sign-In จึงไม่มีรหัสผ่านให้เปลี่ยน',
      'cannotUseSamePassword': 'รหัสผ่านใหม่ต้องไม่ซ้ำกับรหัสผ่านเดิม',
      'passwordResetNeedsPasswordAccount': 'บัญชีนี้ใช้ Google Sign-In จึงไม่สามารถรีเซ็ตรหัสผ่านได้',
      'confirmSignOutTitle': 'ออกจากระบบ',
      'confirmSignOutMessage': 'คุณแน่ใจหรือไม่ว่าต้องการออกจากระบบ?',
      'confirmSignOutAction': 'ออกจากระบบ',
      'loginTagline': 'ผู้ช่วยของคุณเพื่อความสำเร็จด้านการเรียนและชีวิตนักเรียนที่เป็นระบบ',
      'forgotPassword': 'ลืมรหัสผ่าน?',
      'resetPasswordTitle': 'รีเซ็ตรหัสผ่าน',
      'resetPasswordDescription': 'กรอกอีเมลของคุณ แล้วเราจะส่งลิงก์รีเซ็ตรหัสผ่านให้',
      'enterYourEmail': 'กรอกอีเมลของคุณ',
      'signIn': 'เข้าสู่ระบบ',
      'orContinueWith': 'หรือดำเนินการต่อด้วย',
      'googleSignInSemantic': 'เข้าสู่ระบบด้วย Google',
      'noAccountPrompt': 'ยังไม่มีบัญชีใช่ไหม? ',
      'emailAddress': 'อีเมล',
      'enterEmailAddress': 'กรอกอีเมล',
      'pleaseEnterEmailAddress': 'กรุณากรอกอีเมล',
      'pleaseEnterValidEmailAddress': 'กรุณากรอกอีเมลที่ถูกต้อง',
      'pleaseEnterPassword': 'กรุณากรอกรหัสผ่าน',
      'passwordMinLength': 'รหัสผ่านต้องมีอย่างน้อย 8 ตัวอักษร',
      'signInFailed': 'เข้าสู่ระบบไม่สำเร็จ',
      'noAccountFound': 'ไม่พบบัญชีที่ใช้อีเมลนี้',
      'incorrectPassword': 'รหัสผ่านไม่ถูกต้อง',
      'invalidCredentials': 'อีเมลหรือรหัสผ่านไม่ถูกต้อง',
      'invalidEmailAddress': 'อีเมลไม่ถูกต้อง',
      'accountDisabled': 'บัญชีนี้ถูกปิดใช้งาน',
      'googleSignInFailed': 'เข้าสู่ระบบด้วย Google ไม่สำเร็จ',
      'googleSignInCancelled': 'ยกเลิกการเข้าสู่ระบบด้วย Google',
      'createAccount': 'สร้างบัญชี',
      'signupSubtitle': 'สมัครสมาชิกเพื่อเริ่มใช้งาน PLAZO',
      'alreadyHaveAccountPrompt': 'มีบัญชีอยู่แล้ว? ',
      'fullName': 'ชื่อ-นามสกุล',
      'enterFullName': 'กรอกชื่อ-นามสกุล',
      'pleaseEnterYourName': 'กรุณากรอกชื่อของคุณ',
      'confirmPassword': 'ยืนยันรหัสผ่าน',
      'pleaseConfirmPassword': 'กรุณายืนยันรหัสผ่าน',
      'passwordsDoNotMatch': 'รหัสผ่านไม่ตรงกัน',
      'signUpFailed': 'สมัครสมาชิกไม่สำเร็จ',
      'weakPassword': 'รหัสผ่านไม่ปลอดภัยพอ',
      'emailAlreadyInUse': 'อีเมลนี้ถูกใช้งานแล้ว',
      'lastLogin': 'เข้าสู่ระบบครั้งสุดท้าย',
      'lastLoginNever': 'ยังไม่เคยเข้า',
      'activeSessions': 'เซสชันที่ใช้งานอยู่',
      'currentDevice': 'อุปกรณ์นี้ (ปัจจุบัน)',
      'device': 'อุปกรณ์',
      'lastActivity': 'กิจกรรมล่าสุด',
      'manageDevices': 'จัดการ',
      'securityAlerts': 'การแจ้งเตือนความปลอดภัย',
      'noActiveAlerts': 'ไม่มีการแจ้งเตือน',
      'recentActivity': 'กิจกรรมล่าสุด',
      'viewActivityLog': 'ดูบันทึก',
      'deleteAccount': 'ลบบัญชี',
      'deleteAccountButton': 'ลบบัญชีของฉัน',
      'deleteAccountConfirmTitle': 'ลบบัญชี',
      'deleteAccountConfirmMessage': 'คุณแน่ใจหรือไม่? การกระทำนี้ไม่สามารถคืนได้ จะลบข้อมูลของคุณทั้งหมดอย่างถาวร',
      'deleteAccountWarning': 'คำเตือน: จะลบบัญชีและข้อมูลทั้งหมดอย่างถาวร',
      'accountDeleted': 'ลบบัญชีสำเร็จแล้ว',
      'dataDeletedWarning': 'บัญชีและข้อมูลของคุณถูกลบไปแล้ว',
      'viewPrivacyPolicy': 'ดูนโยบายความเป็นส่วนตัว',
      'privacyPolicy': 'นโยบายความเป็นส่วนตัว',
    },
  };

  static String get(String key, String language) {
    return translations[language]?[key] ?? translations['en']![key]!;
  }
}
